jobs:
 - name: u16
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16"
             imageTag: master
         script:
            - java -version
            - nodejs --version
            - yarn -version
            - source /usr/local/rvm/scripts/rvm
            - ruby -v
            - python -V
            - pip --version
            - virtualenv --version
            - git --version
            - aws --version
            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - git lfs version
            - kubectl version --client
            - kops version
            - helm version --client
            - doctl version
            - ansible --version
            - pip show boto
            - pip show boto3
            - pip show apache-libcloud
            - pip show azure
            - pip show dopy
            - packer --version
            - jq --version
            - terraform --version
            - openstack --version
          
 - name: u16all
   type: runSh
   steps:
     - IN: u16
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16all"
             imageTag: master
         script:
            - ls
          
